### PR TITLE
Proposed revisions for #823 (unique commits)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
Suggested changes to PR betterscientificsoftware/bssw.io#823 made by @markcmiller86.

The commits in the branch were created from the branch in PR betterscientificsoftware/bssw.io#824 by doing:

```
$ cd bssw.io/

$ git checkout 560-git-beginners-usage-tips

$ git fetch github

$ git checkout bc1b95d482e0a8eb50ab09977e8ba43d861c6c2f -- Articles/HowTos/CriticalBeginnerGitUsageTips.md

$ git commit -a --author="miller86 <miller86@llnl.gov>"  # Use same commit message from  bc1b95d482e0a8eb50ab09977e8ba43d861c6c2f

$ git cherry-pick bc1b95d482e0a8eb50ab09977e8ba43d861c6c2f..github/mcm86-560-git-beginners-usage-tips
[560-git-beginners-usage-tips 5dd533f7] fix incorrect refs to implicit anchors
 Author: miller86 <miller86@llnl.gov>
 Date: Thu May 6 21:19:53 2021 -0700
 1 file changed, 2 insertions(+), 2 deletions(-)
[560-git-beginners-usage-tips 204be647] fix sole internal link
 Author: miller86 <miller86@llnl.gov>
 Date: Thu May 6 21:27:09 2021 -0700
 1 file changed, 1 insertion(+), 1 deletion(-)
[560-git-beginners-usage-tips 611098bb] fix teaser
 Author: miller86 <miller86@llnl.gov>
 Date: Thu May 6 21:28:14 2021 -0700
 1 file changed, 1 insertion(+), 1 deletion(-)
[560-git-beginners-usage-tips f10046ff] Fix typo
 Author: Mark C. Miller <miller86@llnl.gov>
 Date: Fri May 7 10:26:46 2021 -0700
 1 file changed, 1 insertion(+), 1 deletion(-)
[560-git-beginners-usage-tips 4a9c80cc] Update CriticalBeginnerGitUsageTips.md
 Author: Mark C. Miller <miller86@llnl.gov>
 Date: Fri May 7 11:00:34 2021 -0700
 1 file changed, 4 insertions(+), 4 deletions(-)
```

Now we can see the diffs in this PR made by @markcmiller86 unique from the commits in PR betterscientificsoftware/bssw.io#823.

### CODE REVIEW

**Comment by markcmiller86** [comment]
LGTM

**Comment by markcmiller86** [comment]
BTW...I am just *stunned* how poorly Git's browser-based diffing and display tool gets this (below). The only thing that has changed on these lines is the last few chars. And, its treating them like wholesale deletes of entire lines and replacements.

Screen Shot 2021-05-07 at 11 42 00 AM

**Comment by bartlettroscoe** [comment]
> BTW...I am just stunned how poorly Git's browser-based diffing and display tool gets this

@markcmiller86, yea, but if you do the side-by-side it is not too bad.   Then there is always the git command-line with `git diff --word-diff` that shows the below diff (image):

image

**Comment by bartlettroscoe** [comment]
> LGTM

@markcmiller86, of course it does.  These are your commits :-)

**Pull request merged**
